name: modul-295-twitter
recipe: laravel
config:
  webroot: public
  php: 8.2
services:
  appserver:
    run:
      - cp -n .env.example .env
      - composer install
  database:
    portforward: 3306
